# General settings
conquerIfWithoutNation: true
conquerIfInNation: true
costStartTownWar: 500
costStartNationWar: 1000
costJoinNationWarAttackers: 500
costJoinNationWarDefenders: 0
secondBetweenAnnounceTimeLeft: 60
secondToConfirmAction: 30
minSecondsBetweenPeaceRequests: 30
daysConqueredIfWithoutNation: 7
daysConqueredIfInNation: 7
nationWarBlocksTransferEvent: 0.1
townWarBlocksTransferPercent: 0.1

# When people can wage war - This is for town wars
# default one week
cooldown-seconds-attackers-lose-attack-same-town: 604800
# default ten minutes
cooldown-seconds-attackers-lose-attack-different-town: 600
# default three days
cooldown-seconds-defenders-lose-attack-by-same-town: 259200
# default one day
cooldown-seconds-defenders-lose-attack-by-different-nation: 86400
# default one week
cooldown-seconds-attackers-lose-attack-same-nation: 604800
# default ten minutes
cooldown-seconds-attackers-lose-attack-different-nation: 600
# default three days
cooldown-seconds-defenders-lose-attack-by-same-nation: 259200
# default one day
cooldown-seconds-defenders-lose-attack-by-different-town: 86400

# first number minumum online
# second number is town size
min-online-to-be-attacked-town-wars:
  - 1, 1
  - 2, 3
  - 3, 5
  - 4, 8
  - 5, 12
  - 6, 18
min-online-to-be-attacked-nation-wars:
  - 1, 1
  - 2, 3
  - 3, 5
  - 4, 8
  - 5, 12
  - 6, 18
  - 7, 24
  - 8, 32
  - 9, 40
  - 10, 50

# How to win the war
tickLimitTownWar: 18000
tickLimitNationWar: 18000
ticksToCaptureTown: 1200
ticksUntilNoLongerInCombat: 300
ticksWithoutAttackersOccupyingUntilDefendersWin: 400
ticksBetweenNotOccupyingWarning: 100
ticksBeforeWarBegins: 1200
ticksToRestoreBrokenBlocks: 1200
ticksToRemovePlacedBlocks: 600
disallow-breaking-blocks-in-war:
  - ITEM_FRAME
  - PAINTING
  - ARMOR_STAND
  - ENDER_CRYSTAL
  - MINECART
  - MINECART_CHEST
  - MINECART_FURNACE
  - MINECART_COMMAND
  - MINECART_HOPPER
allowed-switches-in-war:
  - ACACIA_DOOR
  - OAK_DOOR
  - BIRCH_DOOR
  - CRIMSON_DOOR
  - DARK_OAK_DOOR
  - JUNGLE_DOOR
  - SPRUCE_DOOR
  - WARPED_DOOR
  - STONE_BUTTON
  - OAK_BUTTON
  - SPRUCE_BUTTON
  - BIRCH_BUTTON
  - JUNGLE_BUTTON
  - ACACIA_BUTTON
  - DARK_OAK_BUTTON
  - CRIMSON_BUTTON
  - WARPED_BUTTON
  - POLISHED_BLACKSTONE_BUTTON
  - LEVER
  - OAK_PRESSURE_PLATE
  - SPRUCE_PRESSURE_PLATE
  - BIRCH_PRESSURE_PLATE
  - JUNGLE_PRESSURE_PLATE
  - ACACIA_PRESSURE_PLATE
  - DARK_OAK_PRESSURE_PLATE
  - CRIMSON_PRESSURE_PLATE
  - WARPED_PRESSURE_PLATE
  - POLISHED_BLACKSTONE_PRESSURE_PLATE
  - LIGHT_WEIGHTED_PRESSURE_PLATE
  - HEAVY_WEIGHTED_PRESSURE_PLATE
blacklisted-respawn-blocks:
  - bedrock
  - cactus
  - flowing_lava
  - flowing_water
  - lava
  - oak_leaves
  - spruce_leaves
  - birch_leaves
  - jungle_leaves
  - acacia_leaves
  - dark_oak_leaves
  - stationary_lava
  - stationary_water
  - water